# Generated by Django 6.1 on 2026-08-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('numero', models.CharField(blank=True, max_length=5, null=True)),
                ('nacionalidade', models.CharField(max_length=50)),
            ],
        ),
    ]
