# Generated by Django 6.1 on 2026-08-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('tamanho', models.CharField(blank=True, max_length=10, null=True)),
                ('quantidade_voltas', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
