# Generated by Django 6.1 on 2026-08-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0002_pista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Minha Equipe F1', max_length=100)),
                ('orcamento', models.DecimalField(decimal_places=2, default=100000000.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='FornecedorMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('potencia', models.IntegerField(default=80)),
                ('confiabilidade', models.IntegerField(default=80)),
                ('preco', models.DecimalField(decimal_places=2, default=5000000.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pagamento_por_corrida', models.DecimalField(decimal_places=2, default=250000.0, max_digits=10)),
                ('meta_posicao', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='piloto',
            name='habilidade',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='pista',
            name='chance_safety_car',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='pista',
            name='desgaste_pneus',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='pista',
            name='exigencia_motor',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='nacionalidade',
            field=models.CharField(default='Desconhecida', max_length=50),
        ),
        migrations.AlterField(
            model_name='pista',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pista',
            name='pais',
            field=models.CharField(default='Desconhecido', max_length=50),
        ),
        migrations.AlterField(
            model_name='pista',
            name='quantidade_voltas',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='pista',
            name='tamanho',
            field=models.FloatField(default=5.0),
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aerodinamica', models.IntegerField(default=40)),
                ('chassi_peso', models.IntegerField(default=40)),
                ('equipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simulador.equipe')),
            ],
        ),
        migrations.AddField(
            model_name='piloto',
            name='equipe_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.equipe'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='motor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.fornecedormotor'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='patrocinadores',
            field=models.ManyToManyField(blank=True, to='simulador.patrocinador'),
        ),
    ]
