# Generated by Django 6.1 on 2026-08-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0003_equipe_fornecedormotor_patrocinador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='controlada_pelo_jogador',
            field=models.BooleanField(default=False),
        ),
    ]
