# Generated by Django 6.1 on 2026-08-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0004_equipe_controlada_pelo_jogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='categoria',
            field=models.CharField(choices=[('ATUAL', 'Grid Atual'), ('CLASSICA', 'Equipe Clássica'), ('ORIGINAL', 'Criada pelo Jogador')], default='ATUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
