# Generated by Django 6.1 on 2026-08-14 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0005_equipe_categoria_alter_equipe_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=2026)),
                ('etapa_atual', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('etapa_publicacao', models.IntegerField(default=1)),
                ('temporada_relacionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.temporada')),
            ],
        ),
        migrations.CreateModel(
            name='EtapaCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.pista')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas', to='simulador.temporada')),
            ],
        ),
    ]
