# Generated by Django 6.1 on 2026-08-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0006_temporada_noticias_etapacalendario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piloto',
            old_name='habilidade',
            new_name='nivel_ataque',
        ),
        migrations.AddField(
            model_name='piloto',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='pilotos/'),
        ),
        migrations.AddField(
            model_name='piloto',
            name='nivel_defesa',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='piloto',
            name='ritmo_classificacao',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='piloto',
            name='ritmo_corrida',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='piloto',
            name='xp_acumulado',
            field=models.IntegerField(default=0),
        ),
    ]
