# Generated by Django 6.1 on 2026-08-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0007_rename_habilidade_piloto_nivel_ataque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='pontos_campeonato',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piloto',
            name='pontos_campeonato',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='orcamento',
            field=models.DecimalField(decimal_places=2, default=15000000.0, max_digits=15),
        ),
    ]
